// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Zn_zkSSPJ6ZLsuGhjZWN0nXs3zdQXIE',
    appId: '1:32966899671:android:e194175723563c298cbd92',
    messagingSenderId: '32966899671',
    projectId: 'perfectdiet-8631f',
    databaseURL: 'https://perfectdiet-8631f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'perfectdiet-8631f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcRdOqEs70-12AA_KtprvmpsEnnKUopHA',
    appId: '1:32966899671:ios:5393ee95b3ff7c8b8cbd92',
    messagingSenderId: '32966899671',
    projectId: 'perfectdiet-8631f',
    databaseURL: 'https://perfectdiet-8631f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'perfectdiet-8631f.appspot.com',
    iosClientId: '32966899671-ql2g27ipg5qhjlvqu0a1qo5olma8ndcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.skiripsiApp',
  );
}
